### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by Jbock2015** [cravelight/lazygis-featurecollector#4]
http://arcgisweb.jacksongov.org/arcgis/rest/services/addressing/addresspoints/MapServer/0

Processing PublishGISData.DBO.Editable_Addresses (Feature Layer, 371406 records)
Exception of type 'System.OutOfMemoryException' was thrown.
PublishGISData.DBO.Editable_Addresses finished with errors.

**Comment by cravelight** [comment]
Yup - same as #3 

I'm going to have to break layers with a lot of records into multiple files.  We're hitting a memory threshold on the big ones.

**Comment by Jbock2015** [comment]
Okay, I wasn't sure if it was an issue with my system or the number of
records within the layer.

_Josie Bock, GISP_
_Director of GIS Services_
_Sprocket LLC_
_Rural First GPS Tracking Solutions_
_www.ruralfirst.com http://www.ruralfirst.com_
_Toll free: 844-GPS-INFO_

**Comment by cravelight** [comment]
Not your machine. 

Looks like it’s hitting a limit in .NET

**Comment by cravelight** [comment]
corrected with file split

**Comment by Jbock2015** [comment]
It's seems to be working!!!

_Josie Bock, GISP_
_Director of GIS Services_
_Sprocket LLC_
_Rural First GPS Tracking Solutions_
_www.ruralfirst.com http://www.ruralfirst.com_
_Toll free: 844-GPS-INFO_
